### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by tiaz63** [curasystems/node-bsdiff#1]
I want to use [Sourcegraph](https://sourcegraph.com) for node-bsdiff code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/curasystems/node-bsdiff. (It should only take 30 seconds.)

Thank you!

**Comment by matthiasg** [comment]
what exactly does this do ?

**Comment by matthiasg** [comment]
why does sourcegraph need write access to commits ? what exactly does this mean ?

```
This application will be able to read and write commit statuses (no direct code access).
```

**Comment by matthiasg** [comment]
closed since no feedback
